use_frameworks!

platform :ios, '9.0'

target 'BluetoothMessager_Example' do
  pod 'BluetoothMessager', :path => '../'

  target 'BluetoothMessager_Tests' do
    inherit! :search_paths

    
  end
end
